JBD.MonitorCozinha.WebAdmin/Controllers/EmpresaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Net.Mail;
using System.Threading.Tasks;
using AutoMapper;
using JBD.MonitorCozinha.CrossCutting;
using JBD.MonitorCozinha.Domain.Enuns;
using JBD.MonitorCozinha.WebAdmin.Models;
using JBD.MonitorCozinha.WebAdmin.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace JBD.MonitorCozinha.WebAdmin.Controllers
{
    public class EmpresaController : Controller
    {
        private readonly IMapper _mapper;
        private readonly EmpresaServiceWeb _empresaServiceWeb;
        private readonly UsuarioServiceWeb _usuarioServiceWeb;
        private readonly EmailService emailService;

        public EmpresaController(IMapper mapper)
        {
            _mapper = mapper;
            _empresaServiceWeb = new EmpresaServiceWeb(_mapper);
            _usuarioServiceWeb = new UsuarioServiceWeb(_mapper);
            emailService = new EmailService();
        }

        // GET: Empresa
        public ActionResult Index()
        {
            if (!Controle.ValidarUsuarioLogado()) { return RedirectToAction("Index", "Login"); }
            return View();
        }

        // GET: Empresa
        public ActionResult ListarEmpresas(string nomeEmpresa)
        {
            if (!Controle.ValidarUsuarioLogado()) { return RedirectToAction("Index", "Login"); }

            if (nomeEmpresa != null)
            {
                var empresaDTO = _empresaServiceWeb.ListarEmpresas().Where(c => c.NomeFantasia.ToUpper().Contains(nomeEmpresa.Trim().ToUpper())).ToList();
                List<EmpresaViewModel> empresaVM = new List<EmpresaViewModel>();
                empresaVM = _mapper.Map<List<EmpresaViewModel>>(empresaDTO);
                return PartialView("~/Views/Empresa/_listarEmpresas.cshtml", empresaVM);
            }
            else
            {

                List<EmpresaViewModel> empresasViewModel = new List<EmpresaViewModel>();
                EmpresaViewModel empresaVM = new EmpresaViewModel();
                var empresasDTO = _empresaServiceWeb.ListarEmpresas();
                empresasViewModel = _mapper.Map<List<EmpresaViewModel>>(empresasDTO);
                return PartialView("~/Views/Empresa/_listarEmpresas.cshtml", empresasViewModel);
            }
        }

        // GET: Empresa
        public ActionResult ObterUnidadesByEmpresa(int IdEmpresa)
        {
            if (!Controle.ValidarUsuarioLogado()) { return RedirectToAction("Index", "Login"); }

            EmpresaViewModel empresasViewModel = new EmpresaViewModel();
            //EmpresaViewModel empresaVM = new EmpresaViewModel();
            var empresasDTO = _empresaServiceWeb.ObterEmpresa(IdEmpresa);
            empresasViewModel = _mapper.Map<EmpresaViewModel>(empresasDTO);
            return PartialView("~/Views/Unidade/_listarUnidades.cshtml", empresasViewModel);
        }

        // GET: Empresa/Details/5
        public ActionResult Details(int id)
        {
            if (!Controle.ValidarUsuarioLogado()) { return RedirectToAction("Index", "Login"); }

            return View();
        }

        // POST: Empresa/Create
        [HttpPost]
        public ActionResult SalvarEmpresa(EmpresaViewModel empresa)
        {
            if (!Controle.ValidarUsuarioLogado()) { return RedirectToAction("Index", "Login"); }
            try
            {
                EmpresaViewModel empresaViewModel = new EmpresaViewModel();
                var empresaRetorno = _empresaServiceWeb.CadastrarEmpresa(empresa);

                if(empresaRetorno != null)
                {
                    Random randNum = new Random();
                    var Numero = randNum.Next().ToString().Substring(5);

                    var padraoPassword = "operacional" + Numero + empresaRetorno.IdEmpresa.ToString();
                    var usuarioViewModel = new UsuarioViewModel()
                    {
                        IdUsuario = 0,
                        IdEmpresa = empresaRetorno.IdEmpresa,
                        IdUnidade = 0,
                        IdPessoa = 0,
                        IdTipo = TipoUsuarioEnum.Operacional,
                        IdStatus = (int)StatusEnum.Ativo,
                        UserName = "operacional",
                        Password = GeraradorDeHash.GerarHash256(padraoPassword),
                        DataCadastro = DateTime.Now,
                        Pessoa = null,
                        Unidade = null
                    };

                    var usuario = _usuarioServiceWeb.CadastrarUsuario(usuarioViewModel);

                    if (usuario.IdUsuario > 0)
                    {
                        string mensagem = "";
                        string email = empresaRetorno.Email;

                        mensagem = "<html><head><title>Dados para acesso</title></head><body>";
                        mensagem += "<h1>Olá " + empresaRetorno.NomeContato + "</h1>";
                        mensagem += "<p>Segue as informações para acessar o Monitor de Cozinha.</p>";
                        mensagem += "<p></p>";
                        mensagem += "<p>Usuário: " + usuario.UserName + "</p>";
                        mensagem += "<p>Senha: " + padraoPassword + "</p>";
                        mensagem += "<p>Este usuário lhe dará o acesso necessário aos recursos do Monitor de TV, para cadastrar novas senha e administra-las</p>";
                        mensagem += "<p>http://www.mymonitor.com.br</p>";
                        mensagem += "</body></html>";

                        //Enviar e-mail para acesso
                        var retorno = emailService.EnvioEmail(email, mensagem);
                    }
                }

                return Json(new { mensagem = "Registro salvo com sucesso", retorno = "200" });
            }
            catch (Exception ex)
            {
                return Json(new { mensagem = "Ocorreu um erro ao tentar gravar os dados", retorno = "402" });
            }
        }

        // GET: Empresa/Edit/5
        public ActionResult EditarEmpresa(int id)
        {
            if (!Controle.ValidarUsuarioLogado()) { return RedirectToAction("Index", "Login"); }

            EmpresaViewModel empresaVM = new EmpresaViewModel();
            empresaVM = _empresaServiceWeb.ObterEmpresa(id);
            return Json(new { retorno = 200, data = empresaVM });
        }

        // POST: Empresa/Edit/5
        [HttpPost]
        public ActionResult EditarEmpresa(int id, EmpresaViewModel empresa)
        {
            if (!Controle.ValidarUsuarioLogado()) { return RedirectToAction("Index", "Login"); }

            try
            {
                return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: Empresa/Delete/5
        public ActionResult Delete(int id)
        {
            if (!Controle.ValidarUsuarioLogado()) { return RedirectToAction("Index", "Login"); }
            var empresa = _empresaServiceWeb.ObterEmpresa(id);
            empresa.IdStatus = (int)StatusEnum.Excluido;
            empresa.Unidades = null;
            _empresaServiceWeb.CadastrarEmpresa(empresa);
            return Json(new { mensagem = "Registro excluído com sucesso", retorno = "200" });
        }

        // POST: Empresa/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            if (!Controle.ValidarUsuarioLogado()) { return RedirectToAction("Index", "Login"); }

            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public ActionResult VeficaDuplicidadeCnpjCpf(string cnpjcpf)
        {
            var mensagem = "";
            bool retorno = false;
            try
            {
                EmpresaServiceWeb empresaServiceWeb = new EmpresaServiceWeb(_mapper);
                retorno = empresaServiceWeb.VeficaDuplicidadeCnpjCpf(cnpjcpf);

                if (retorno)
                {
                    mensagem = "CNPJ está cadastrado, por favor verifique";
                }
            }
            catch (Exception)
            {
                mensagem = "Ocorreu um erro na veriificação do CNPJ";
            }

            return Json(new { retorno = 200, duplicado = retorno, mensagem = mensagem });
        }
    }
}

JBD.MonitorCozinha.WebAdmin/Controllers/UnidadeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using AutoMapper;
using JBD.MonitorCozinha.CrossCutting;
using JBD.MonitorCozinha.Domain.Enuns;
using JBD.MonitorCozinha.WebAdmin.Models;
using JBD.MonitorCozinha.WebAdmin.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace JBD.MonitorCozinha.WebAdmin.Controllers
{
    public class UnidadeController : Controller
    {
        private readonly IMapper _mapper;
        private readonly UnidadeServiceWeb _unidadeServiceWeb;
        private readonly UsuarioServiceWeb _usuarioServiceWeb;
        private readonly EmailService emailService;

        public UnidadeController(IMapper mapper)
        {
            _mapper = mapper;
            _unidadeServiceWeb = new UnidadeServiceWeb(_mapper);
            _usuarioServiceWeb = new UsuarioServiceWeb(_mapper);
            emailService = new EmailService();
        }

        // GET: Unidade
        public ActionResult Index(int IdEmpresa = 0)
        {
            var unidadeViewModel = new UnidadeViewModel();
            unidadeViewModel.IdEmpresa = IdEmpresa;

            var nomeEmpresa = new UnidadeViewModel();

            //Recuperando Nome Empresa por Nome Fantasia
            EmpresaServiceWeb empresaServiceWeb = new EmpresaServiceWeb(_mapper);
            var nome = empresaServiceWeb.ObterEmpresa(IdEmpresa).NomeFantasia;

            //var Nomeaqui = nome.RazaoSocial;
            unidadeViewModel.NomeEmpresa = nome;
          

            return View(unidadeViewModel);
        }

        public ActionResult ListarUnidades(string nomeUnidade, int IdEmpresa)
        {
            var empresaViewModel = new EmpresaViewModel();


            if (nomeUnidade != null)
            {
                EmpresaServiceWeb unidadeServiceWeb = new EmpresaServiceWeb(_mapper);
                //List<EmpresaViewModel> empresaViewModel = new List<EmpresaViewModel>();

                var empresaVM = unidadeServiceWeb.ObterEmpresa(IdEmpresa);

                empresaViewModel = empresaVM;               
                var unidades = empresaVM.Unidades.Where(c => c.Nome.ToUpper().Contains(nomeUnidade.Trim().ToUpper())).ToList();
                empresaViewModel.Unidades = new List<UnidadeViewModel>();

                empresaViewModel.Unidades.AddRange(unidades);

                return PartialView("~/Views/Unidade/_listarUnidades.cshtml", empresaViewModel);

            }
            else
            {

                // empresaViewModel = new EmpresaViewModel();
                if (IdEmpresa > 0)
                {
                    empresaViewModel = ObterListaUnidades(IdEmpresa);
                }

            }
            return PartialView("~/Views/Unidade/_listarUnidades.cshtml", empresaViewModel);


        }

        // GET: Unidade/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Unidade/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Unidade/Create
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult SalvarUnidade(UnidadeViewModel unidade)
        {
            try
            {
                unidade = _unidadeServiceWeb.CadastrarUnidade(unidade);

                if (unidade != null)
                {
                    Random randNum = new Random();
                    var Numero = randNum.Next().ToString().Substring(5);

                    var padraoPassword = "cozinha" + Numero + unidade.IdUnidade;
                    var usuarioViewModel = new UsuarioViewModel()
                    {
                        IdUsuario = 0,
                        IdEmpresa = unidade.IdEmpresa,
                        IdUnidade = unidade.IdUnidade,
                        IdPessoa = 0,
                        IdTipo = TipoUsuarioEnum.Cozinha,
                        IdStatus = (int)StatusEnum.Ativo,
                        UserName = "cozinha",
                        Password = GeraradorDeHash.GerarHash256(padraoPassword),
                        DataCadastro = DateTime.Now,
                        Pessoa = null,
                        Unidade = null
                    };

                    var usuario = _usuarioServiceWeb.CadastrarUsuario(usuarioViewModel);

                    if (usuario.IdUsuario > 0)
                    {
                        string mensagem = "";
                        string email = unidade.Email;

                        mensagem = "<html><head><title>Dados para acesso</title></head><body>";
                        mensagem += "<h1>Olá " + unidade.NomeContato + "</h1>";
                        mensagem += "<p>Segue as informações para acessar o Monitor de Cozinha.</p>";
                        mensagem += "<p></p>";
                        mensagem += "<p>Usuário: " + usuario.UserName + "</p>";
                        mensagem += "<p>Senha: " + padraoPassword + "</p>";
                        mensagem += "<p>http://www.mymonitor.com.br</p>";
                        mensagem += "<p>Este usuário lhe dará acesso aos recursos do Monitor de Administrativo, para atualizar o andamento das senha</p>";
                        mensagem += "</body></html>";

                        //Enviar e-mail para acesso
                        var retorno = emailService.EnvioEmail(email, mensagem);
                    }
                }

                return Json (new {mensagem = "Registro salvo com sucesso", retorno = "200" });
            }
            catch(Exception ex)
            {
                return Json(new { mensagem = "Ocorreu um erro ao tentar salvar a unidade", retorno = "400" });
            }
        }

        // GET: Unidade/Edit/5
        public ActionResult EditarUnidade(int id)
        {

            UnidadeServiceWeb unidadeServiceWeb = new UnidadeServiceWeb(_mapper);
            UnidadeViewModel unidadeVM = new UnidadeViewModel();

            unidadeVM = unidadeServiceWeb.ObterUnidade(id);


            return Json(new { retorno = 200, data = unidadeVM });
        }

        // POST: Unidade/Edit/5
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult EditarUnidade(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Unidade/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Unidade/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        #region Methods

        private EmpresaViewModel ObterListaUnidades(int IdEmpresa)
        {
            //UnidadeServiceWeb unidadeServiceWeb = new UnidadeServiceWeb(_mapper);
            EmpresaServiceWeb unidadeServiceWeb = new EmpresaServiceWeb(_mapper);

            EmpresaViewModel unidadesViewModel = new EmpresaViewModel();
            var unidadesDTO = unidadeServiceWeb.ObterEmpresa(IdEmpresa);
         
            unidadesViewModel = _mapper.Map<EmpresaViewModel>(unidadesDTO);

            return unidadesViewModel;
        }

        #endregion
    }
}

JBD.MonitorCozinha.WebAdmin/Views/Unidade/Index.cshtml
@model JBD.MonitorCozinha.WebAdmin.Models.UnidadeViewModel

<div id="mensagem" name="mensagem" style="display: none; background-color: #ff2d296b; text-align:center; height: 40px; padding-top: 5px; font-size: 20px;"><b>mensagem</b></div>
<div class="row" style=" display: contents !important; text-align:center;">
    <div style="background-color: #F2F2F2">
        <h3 class="modal-title" style="background-color: #e9ecef; margin-right: 5px; margin-left: 5px;">Empresa: @Model.NomeEmpresa</h3>
    </div>
</div>

<div class="jumbotron row topJumboTrom" id="TopoPesquisa" >

    @*Recebe Id empresa para passar no Unidade.JS*@
    <input type="hidden" id="IdEmpresa" value="@Model.IdEmpresa" />
    <div class="col-md-12 form-inline" style="">
        <div class="col-md-2" style="text-align:-webkit-right ; padding-top: 5px;">
            <lable style="font-size:18px ;">Nome Unidade</lable>
        </div>

        <div class="col-md-4">
            <input type="text" class="form-control" id="UnidadePesquisar" name="UnidadePesquisar" style="width:inherit;" />
        </div>
        <div class="col-md-1" style="padding-right: 80px">
            <button class="btn btn-primary" id="btPesquisar">Pesquisar</button>
        </div>

        <div class="col-md-1" style="padding-right: 80px">
            <button class="btn btn-primary" id="btNovo">Cadastrar</button>
        </div>
        <div class="col-md-1" style="padding-right: 80px">
            @Html.ActionLink("Voltar", "Index", "Empresa", null, new {@class = "btn btn-primary" })
            @*<button class="btn btn-primary" id="btVoltar" style="align-content:flex-end">Voltar</button>*@

        </div>

    </div>
</div>

<div id="divListarUnidades"></div>

@*<script src="~/js/Views/Unidade/Unidade.js"></script>*@

<!-- Modal para cadastrar cliente -->

<div class="modal fade" id="ModalCadastrarUnidade" tabindex="-1" role="dialog" aria-labelledby="fatorFModalLabel" aria-hidden="true" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog border-dark">
        <div class="modal-content" style="width: 200%; margin-left: -50%;">
            <!-- Modal Header -->
            <div id="mensagemModal" name="mensagem" style="display: none; background-color: #ff2d296b; text-align:center; height: 40px; padding-top: 5px; font-size: 20px;"><b>mensagem</b></div>

            <div class="modal-header">
                <div class="col-md-11">
                    <h3 class="modal-title">Cadastrar Unidade</h3>
                </div>
                <div class="col-md-1">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
            </div>
            <!-- Modal body -->
            <!--------------------------------------------------->

            @using (Html.BeginForm("Salvar", "Unidade", FormMethod.Post, new { name = "frmCliente", id = "frmCliente" }))
            {
                @Html.AntiForgeryToken()
                <input type="hidden" id="IdUnidade" value="" />


                <fieldset>
                    <legend>@ViewBag.Title</legend>
                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        <div class="form-group row col-md-12">
                            <div class="form-group col-md-8">
                                @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-8" })
                                <div class="col-md-12">
                                    @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control", @maxlength = "60" } })
                                    @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group col-md-4">
                                @Html.LabelFor(model => model.CEP, htmlAttributes: new { @class = "control-label col-md-3" })
                                <div class="col-md-12">
                                    @Html.EditorFor(model => model.CEP, new { htmlAttributes = new { @class = "form-control cepClass", @maxlength = "9" } })
                                    @Html.ValidationMessageFor(model => model.CEP, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div class="form-group row col-md-12">
                            <div class="form-group col-md-6">
                                @Html.LabelFor(model => model.Endereco, htmlAttributes: new { @class = "control-label col-md-3" })
                                <div class="col-md-12">
                                    @Html.EditorFor(model => model.Endereco, new { htmlAttributes = new { @class = "form-control", @maxlength = "60" } })
                                    @Html.ValidationMessageFor(model => model.Endereco, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group col-md-2">
                                @Html.LabelFor(model => model.Numero, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-12">
                                    @Html.EditorFor(model => model.Numero, new { htmlAttributes = new { @class = "form-control", @maxlength = "10" } })
                                    @Html.ValidationMessageFor(model => model.Numero, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group col-md-4">
                                @Html.LabelFor(model => model.Bairro, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-12">
                                    @Html.EditorFor(model => model.Bairro, new { htmlAttributes = new { @class = "form-control", @maxlength = "60" } })
                                    @Html.ValidationMessageFor(model => model.Bairro, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div class="form-group row col-md-12">
                            <div class="form-group col-md-6">
                                @Html.LabelFor(model => model.Cidade, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-12">
                                    @Html.EditorFor(model => model.Cidade, new { htmlAttributes = new { @class = "form-control", @maxlength = "60" } })
                                    @Html.ValidationMessageFor(model => model.Cidade, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group col-md-2">
                                @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-12">
                                    @Html.EditorFor(model => model.Estado, new { htmlAttributes = new { @class = "form-control", @maxlength = "60" } })
                                    @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group col-md-4">
                                <label>
                                    @Html.LabelFor(model => model.Pais, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-12">
                                        <select id="Pais" class="form-control"></select>
                                    </div>
                                </label>
                            </div>
                        </div>

                        <div class="form-group row col-md-12">
                            <div class="form-group col-md-8">
                                @Html.LabelFor(model => model.NomeContato, htmlAttributes: new { @class = "control-label col-md-12" })
                                <div class="col-md-12">
                                    @Html.EditorFor(model => model.NomeContato, new { htmlAttributes = new { @class = "form-control", @maxlength = "50" } })
                                    @Html.ValidationMessageFor(model => model.NomeContato, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group col-md-4">
                                @Html.LabelFor(model => model.Telefone, htmlAttributes: new { @class = "control-label col-md-12" })
                                <div class="col-md-12">
                                    @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control", @maxlength = "15" } })
                                    @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div class="form-group row col-md-12">
                            <div class="form-group col-md-12">
                                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-12" })
                                <div class="col-md-12">
                                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @maxlength = "100" } })
                                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <input type="hidden" id="DataCadastro" value="@DateTime.Now" />
                            <input type="hidden" id="IdStatus" value="" />
                            <input type="hidden" id="idEmpresaNum" value="@Model.IdEmpresa" />

                        </div>
                    </div>
                </fieldset>
            }

            <!--------------------------------------------------->
            <!-- Modal footer -->
            <div class="modal-footer" style="display:grid">
                <div class="col-md-12" style="align-content: flex-end">
                    <button id="btnFecharUnidade" type="button" class="btn btn-danger">&nbsp;&nbsp;&nbsp;Fechar&nbsp;&nbsp;&nbsp;</button>
                    <button id="btnSalvarUnidade" type="button" class="btn btn-outline-success">&nbsp;&nbsp;&nbsp;Salvar&nbsp;&nbsp;&nbsp;</button>

                </div>
            </div>

        </div>
    </div>
</div>

JBD.MonitorCozinha.WebAdmin/Views/Unidade/_listarUnidades.cshtml
@model JBD.MonitorCozinha.WebAdmin.Models.EmpresaViewModel

<table class="table table-striped table-bordered table-hover" id="tbListarUnidades">
    <thead>
        <tr>
            <th>
                Nome Unidade
            </th>
            <th>
                CEP
            </th>
            <th>
                Endereço
            </th>
            <th>
                Bairro
            </th>
            <th>
                Cidade
            </th>
            <th>
                Estado
            </th>
            <th>
                Pais
            </th>
            <th style="width:150px;"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Unidades)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CEP)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Endereco)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Bairro)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cidade)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Estado)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Pais)
                </td>
                <td>
                    <a href="javascript:;" onclick="Unidade.Editar(@item.IdUnidade)" title="Editar unidade"><i class="fas fa-edit"></i></a>
                    <a href="javascript:;" onclick="Unidade.Excluir(@item.IdUnidade)" title="Excluir unidade"><i class="fas fa-trash"></i></a>
                    <span style="font-size:25px;">&nbsp;|&nbsp;</span>
                    <a href="javascript:;" onclick="Unidade.ListarPessoa(@item.IdUnidade)" title="Lista de usuários"><i class='fas fa-user-plus'></i></a>
                </td>
            </tr>
        }
    </tbody>
</table>
<script src="~/lib/fontawesome/fontawesome-free-5.9.0-web/js/all.js"></script>